### ISSUE TITLE
How do I correct the flutter path if I first set it incorrectly.

### ISSUE THREAD

**Issue by thuanict** [nEdAy/Flutter-Build-Runner-Helper#4]
When I run the plugin in Android Studio, it shows this error:

`Could not running build! message: Cannot run program ...... error = 13, Permission denied.`

Maybe I setup the Flutter SDK path not correct. How I change the Flutter path?

**Comment by nEdAy** [comment]
If you use the latest version, you can modify the flutter path in the Preference.
Make sure that the selected path is the {Flutter SDK Path}/bin/flutter.

Preferences -> Flutter Build Runner Helper
or
Preferences -> Other Settings -> Flutter Build Runner Helper
