### ISSUE TITLE
Compatibility with Intellij IDEA ?

### ISSUE THREAD

**Issue by iangregsondev** [nEdAy/Flutter-Build-Runner-Helper#6]
On the plugin page (jetbrains) it states its only compatible with Android Studio.

Considering android studio was built from intellij, would it not make sense to allow it to be installed on intellij also ?

I presume that you need to publish the plugin saying its compatible with intellij ?

Any ideas ?

Thanks in advance

**Comment by nEdAy** [comment]
Thanks for the feedback.
The IDE recommended by Flutter is AndroidStudio and VSCode.
I use AndroidStudio for my daily development. I haven't used IDEA development Flutter yet.
But it should be easy for this plugin to be compatible with IDEA.
I will try it and look forward to the next version.

**Comment by nEdAy** [comment]
Modify Flutter Build Runner Helper 1.7 Supported Products:
Android Studio, IntelliJ IDEA Ultimate, IntelliJ IDEA Community, IntelliJ IDEA Educational, WebStorm

Compatibility verification
IntelliJ IDEA Ultimate IU-181.5684.4 (2018.1.8)Compatible
IntelliJ IDEA Ultimate IU-182.5262.2 (2018.2.8)Compatible
IntelliJ IDEA Ultimate IU-183.6156.11 (2018.3.6)Compatible
IntelliJ IDEA Ultimate IU-191.8026.42 (2019.1.4)Compatible
IntelliJ IDEA Ultimate IU-192.7142.36 (2019.2.4)Compatible
IntelliJ IDEA Ultimate IU-193.7288.26 (2019.3.5)Compatible
IntelliJ IDEA Ultimate IU-201.8743.12 (2020.1.4)Compatible
IntelliJ IDEA Ultimate IU-202.6397.94 (2020.2)Compatible
IntelliJ IDEA Ultimate IU-202.6948.36Waiting

Version 1.8 ->
Modify the Project SDK to IntelliJ IDEA IU-201.8743.12.

Thank you! The plugin has been submitted for moderation. The request will be processed within two business days.

**Comment by iangregsondev** [comment]
Great! - Thank you.
