### ISSUE TITLE
Rename tab "Flutter Build Runner Console Tool"

### ISSUE THREAD

**Issue by DFelten** [nEdAy/Flutter-Build-Runner-Helper#8]
Thanks for this IntelliJ addon! One suggestion, a possibility to rename the tab would be great.

"Flutter Build Runner Console Tool" is very long and I would like to rename it to for example "Build Runner".

**Comment by nEdAy** [comment]
Thanks.
It's really too long.
Taking your advice, I will update this in the next release.

**Comment by nEdAy** [comment]
Has been fixed and merged.
